# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20181217_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True, verbose_name='Course ID')),
            ],
        ),
    ]
